### ISSUE TITLE
The Arise Problems

### ISSUE THREAD

**Issue by Unfellowed** [Psykotikism/Mutant_Tanks#118] opened 2024-02-10 16:34 UTC
Hello, I want to report to you some problems.
1. Trigger the range ability when the Mutant Tank spawns does not work.
https://youtu.be/EjOlKX_zgB4
2. "Vampire Ability" don't make them harder to kill.
https://youtu.be/44-t46WOjkk
3. Special Infected is not invisible when spawning (in version 8.99 works). And can you remove glow when they control the survivors? Thank you!
https://youtu.be/xyPn1xb15Bs

**Comment by Psykotikism** [comment] 2024-03-14 23:53
> Hello, I want to report to you some problems.
> 
> 1. Trigger the range ability when the Mutant Tank spawns does not work.
>    https://youtu.be/EjOlKX_zgB4
> 2. "Vampire Ability" don't make them harder to kill.
>    https://youtu.be/44-t46WOjkk
> 3. Special Infected is not invisible when spawning (in version 8.99 works). And can you remove glow when they control the survivors? Thank you!
>    https://youtu.be/xyPn1xb15Bs

1. This will be fixed in v9.1.
2. I'm not sure what I can do about this because the breakpoints are handled by the game. I'm not adding any extra damage to survivors or infected related to the Vampire ability. This can happen to other abilities too like Regen.
3. I do not know how to remove the default glow. You need to show your settings for the Ghost ability so I can test the invisibility feature.

**Comment by Unfellowed** [comment] 2024-03-16 18:27
Well, please check and edit my config file.
[mutant_tanks.txt](https://github.com/Psykotikism/Mutant_Tanks/files/14624737/mutant_tanks.txt)
In the next version, can you add these two features to LastBoss? Thank you!
> Reflesh - Special Tank extinguish his own fire when form is changed.
Fenix Tail - Special Tank spawns in forth form when rescue vehicle has come.

One thing I noticed is the abilities are disabled as soon as the SI dies.

https://github.com/Psykotikism/Mutant_Tanks/assets/115072518/f8161796-24c3-41d1-8276-08b04531a25d

**Comment by Psykotikism** [comment] 2024-03-17 05:51
> Well, please check and edit my config file. [mutant_tanks.txt](https://github.com/Psykotikism/Mutant_Tanks/files/14624737/mutant_tanks.txt)

I checked your config file. For the Jockey with Ghost ability, you have these settings:
```cpp
"Ghost Ability"
{
	"Special"
	{
		"Ability Enabled"			"2"
		"Ghost Fade Alpha"			"5"
		"Ghost Fade Delay"			"9999"
		"Ghost Fade Limit"			"50"
		"Ghost Fade Rate"			"0.1"
		"Ghost Specials"			"0"
	}
}
```
With these settings, the Jockey will not be fully invisible. The ability seems to work as intended.

> In the next version, can you add these two features to LastBoss? Thank you!
> > Reflesh - Special Tank extinguish his own fire when form is changed.
> > Fenix Tail - Special Tank spawns in forth form when rescue vehicle has come.

Reflesh is already automatically done for mutants that use the "Boss" feature. See default config and look for Tanks #118-121 for examples of the "Boss" feature.
Fenix Tail can be set up by yourself in the config file. Just set your boss mutant to spawn when rescue vehicle arrives. See INFORMATION.md for the `Finale Types` setting.

> One thing I noticed is the abilities are disabled as soon as the SI dies.
> 
>  2024-03-17.00-44-09.mp4

Yes, that is normal. I do not want abilities to continue after mutants die.

**Closed** 2024-03-17 06:39 UTC
